spring.application.name=Capricorn Adventures

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}
#spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

# Frontend URL for links sent in emails
app.frontend.url=http://localhost:5173

# Email Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration

app.jwt.secret=${JWT_SECRET}
# 1 hour in milliseconds
app.jwt.access-token-expiry=3600000
# 30 days in milliseconds
app.jwt.refresh-token-expiry=2592000000

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173

# Google OAuth2 Configuration

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/google

# PayHere Configuration
payhere.base.url=https://sandbox.payhere.lk/merchant/v1
payhere.merchant.id=${PAYHERE_MERCHANT_ID}
payhere.merchant.secret=${PAYHERE_MERCHANT_SECRET}
payhere.app.id=${PAYHERE_APP_ID}
payhere.app.secret=${PAYHERE_APP_SECRET}
