spring.application.name=Capricorn Adventures

//spring.datasource.url=${DB_URL}
//spring.datasource.username=${DB_NAME}
//spring.datasource.password=${DB_PASSWORD}

//spring.jpa.hibernate.ddl-auto=none
//spring.jpa.show-sql=true
//spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true
# Set the database URL (this tells it to run in memory 'mem' and names it 'capricorn_db')
spring.datasource.url=jdbc:h2:mem:capricorn_db
spring.datasource.driverClassName=org.h2.Driver

# Default credentials for H2
spring.datasource.username=sa
spring.datasource.password=

# Tell Hibernate to use the H2 dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Defer the execution of data.sql until Hibernate finishes creating the schema
spring.jpa.defer-datasource-initialization=true

# Enable the H2 console so you can view your data in a browser (optional but highly recommended!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.forward-headers-strategy=framework
