spring.application.name=Capricorn Adventures

#spring.datasource.url=jdbc:postgresql://ep-floral-darkness-a9lkugol.gwc.azure.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb
#spring.datasource.password=npg_dUhYqVQ3R1LX

spring.datasource.url=jdbc:postgresql://localhost:5432/capricornDB
spring.datasource.username=capricorn_user
spring.datasource.password=CAPRIcorn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true


# JWT

app.jwt.secret=sydusadyuwdwodjcbshcksjcjsdywodcw
app.jwt.access-token-expiry=900000
# 15 minutes in ms
app.jwt.refresh-token-expiry=2592000000
# 30 days in ms

server.port=8080

# #  Google OAuth2 

 spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
 spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
 spring.security.oauth2.client.registration.google.scope=email,profile
 spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}

# # Email 
 spring.mail.host=smtp.gmail.com
 spring.mail.port=587
 spring.mail.username=your-email@gmail.com
 spring.mail.password=your-app-password
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:5173

# CORS 
app.cors.allowed-origins=http://localhost:5173