spring.application.name=Capricorn Adventures

spring.datasource.url=jdbc:postgresql://localhost:5432/colombo_water_front
spring.datasource.username=postgres
spring.datasource.password=1844
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true


# JWT

app.jwt.secret=sydusadyuwdwodjcbshcksjcjsdywodcw
app.jwt.access-token-expiry=900000
# 15 minutes in ms
app.jwt.refresh-token-expiry=2592000000
# 30 days in ms

server.port=8081

# #  Google OAuth2 

spring.security.oauth2.client.registration.google.client-id=710090872493-tplgh8urfo44201cn50or7vbpt2jkjis.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# # Email 
# # Email
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=imansabodini1@gmail.com
spring.mail.password=qlhpwmyzwweyfrck
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=false

app.frontend.url=http://localhost:3000

# # CORS 
app.cors.allowed-origins=http://localhost:3000