name: Deploy Backend

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "vihanchandira" --password-stdin
          docker build -t vihanchandira/backend:latest .
          docker push vihanchandira/backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /opt/app
            docker compose pull backend
            docker compose up -d backend